target:
  relativeDir:   # relative path for code generation
    proto:
    - "{SERVICE_NAME}"
    - "api"
    - "{SERVICE_NAME}"
    client:
    - "{SERVICE_NAME}"
    - "api"
    - "{SERVICE_NAME}"
    server:
    - "{SERVICE_NAME}"
template:
  filesFormatSuffix: ".tmpl"
  protoFilename: "{SERVICE_NAME}.proto.tmpl"
  relativeDir:   # relative path for template
    proto:
    - "proto_template"
    client:
    - "SERVICE"
    - "api"
    - "SERVICE"
    server:
    - "SERVICE"


