target:
  relativeDir:   # relative path for code generation
    proto:
      - "{SERVICE_NAME}Server"
      - "api"
      - "{SERVICE_NAME}"
    client:
      - "{SERVICE_NAME}Server"
      - "api"
      - "{SERVICE_NAME}"
    server:
      - "{SERVICE_NAME}Server"
template:
  filesFormatSuffix: ".tmpl"
  protoFilename: "{SERVICE_NAME}.proto.tmpl"
  relativeDir:   # relative path for template
    proto:
      - "SERVICE"
      - "api"
      - "{SERVICE_NAME}"
    client:
      - "SERVICE"
      - "api"
      - "{SERVICE_NAME}"
#    - "client_template"
    server:
    - "SERVICE"


