target:
  relativeDir:   # relative path for code generation
    proto:
    - "{SERVICE_NAME}Server"
    - "api"
    client:
    - "{SERVICE_NAME}Server"
    - "pkg"
    - "{SERVICE_NAME}"
    server:
    - "{SERVICE_NAME}Server"
template:
  filesFormatSuffix: ".tmpl"
  protoFilename: "{SERVICE_NAME}.proto.tmpl"
  relativeDir:   # relative path for template
    proto:
      - "SERVICE"
      - "api"
#    - "proto_template"
    client:
      - "SERVICE"
      - "pkg"
      - "{SERVICE_NAME}"
#    - "client_template"
    server:
    - "SERVICE"


