target-relative-dir:   # relative path for code generation
  proto:
  - "{SERVICE_NAME}"
  - "api"
  - "{SERVICE_NAME}"
  client:
  - "{SERVICE_NAME}"
  - "api"
  - "{SERVICE_NAME}"
  server:
  - "{SERVICE_NAME}"
template-relative-dir:   # relative path for template
  proto:
  - "SERVICE"
  - "api"
  - "SERVICE"
  client:
  - "SERVICE"
  - "api"
  - "SERVICE"
  server:
  - "SERVICE"

template-proto-filename: "{SERVICE_NAME}.proto.tmpl"

